/* eslint-disable import/prefer-default-export */
export const formData = [
  [
    '11/20/2020 11:27:11',
    '1.0 (24)',
    'Android',
    'Galaxy S9',
    'Yes',
    'Bubah Conteh',
    'contehbub@gmail.com',
    'United States',
    'Male',
    'Under 35',
    'African American/Black, white',
    'Option 1',
    'Indoor low light',
    'No',
    'description',
    '5',
    'some comment',
    '5',
    'some comment',
    '4',
    'some comment',
    '3',
    'some comment',
    'Yes',
    '4',
    'some comment',
    '3',
    'some comment',
    '3',
    'some comment',
    '5',
    'some comment',
    '2',
    'some comment',
    'Yes',
    '2',
    'some comment',
    '5',
    'some comment',
    '5',
    '5',
    'some comment',
    '5',
    'some comment',
    '5',
    'some comment',
    'Yes',
    '2',
    'some comment',
    '5',
    'some comment',
    '5',
    '5',
    'some comment',
    '5',
    'some comment',
    '5',
    'some comment',
    'Yes',
    'some comment',
    'some comment',
    'Yes',
    'some comment',
    'some comment',
    '5',
    'some comment',
    'App is ok',
  ],
];
