/* eslint-disable import/prefer-default-export */
export const formData = [
  [
    '11/20/2020 11:27:11',
    'Yes',
    '1.0 (14)',
    'Bubah Conteh',
    'contehbub@gmail.com',
    'United States',
    'Male',
    'African American/Black, white',
    'Option 1',
    'No',
    'description',
    'Android',
    'Galaxy S9',
    '5',
    'some comment',
    '4',
    'some comment',
    '3',
    'some comment',
    'Indoor low light',
    '4',
    'some comment',
    'Yes',
    '3',
    'some comment',
    '3',
    'some comment',
    '2',
    'No',
    'some comment',
    '2',
    'some comment',
    '2',
    'some comment',
    '5',
    'yes',
    '4',
    'some comment',
    '4',
    'Yes',
    '3',
    'No',
    'Yes',
    'App is ok',
  ],
];
